/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateTaskDialog: typeof import('./components/CreateTaskDialog.vue')['default']
    DownloadItem: typeof import('./components/DownloadItem.vue')['default']
    EditTaskDialog: typeof import('./components/EditTaskDialog.vue')['default']
    HeadersEditor: typeof import('./components/HeadersEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskInfoDialog: typeof import('./components/TaskInfoDialog.vue')['default']
    ToastHost: typeof import('./components/ToastHost.vue')['default']
    UiButton: typeof import('./components/ui/UiButton.vue')['default']
    UiCard: typeof import('./components/ui/UiCard.vue')['default']
    UiCheckbox: typeof import('./components/ui/UiCheckbox.vue')['default']
    UiEmpty: typeof import('./components/ui/UiEmpty.vue')['default']
    UiFormRow: typeof import('./components/ui/UiFormRow.vue')['default']
    UiInput: typeof import('./components/ui/UiInput.vue')['default']
    UiLoadingOverlay: typeof import('./components/ui/UiLoadingOverlay.vue')['default']
    UiModal: typeof import('./components/ui/UiModal.vue')['default']
    UiNumberInput: typeof import('./components/ui/UiNumberInput.vue')['default']
    UiPagination: typeof import('./components/ui/UiPagination.vue')['default']
    UiProgress: typeof import('./components/ui/UiProgress.vue')['default']
    UiSegmented: typeof import('./components/ui/UiSegmented.vue')['default']
    UiSelect: typeof import('./components/ui/UiSelect.vue')['default']
    UiSkeleton: typeof import('./components/ui/UiSkeleton.vue')['default']
    UiSwitch: typeof import('./components/ui/UiSwitch.vue')['default']
    UiTag: typeof import('./components/ui/UiTag.vue')['default']
    UiTextarea: typeof import('./components/ui/UiTextarea.vue')['default']
  }
}
